workflows:
  android-build:
    name: Android App Bundle
    max_build_duration: 30
    environment:
      flutter: "3.19.0"
      java: "17"
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches
    scripts:
      - name: Get dependencies
        script: |
          cd talabtek_app
          flutter pub get
      - name: Build App Bundle
        script: |
          cd talabtek_app
          flutter build appbundle --release --obfuscate --split-debug-info=build/app/outputs/symbols
    artifacts:
      - talabtek_app/build/app/outputs/bundle/release/app-release.aab
      - talabtek_app/build/app/outputs/symbols/**
    publishing:
      email:
        recipients:
          - your-email@example.com